<?php

namespace MainBundle\Repository;

/**
 * ChapterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChapterRepository extends \Doctrine\ORM\EntityRepository
{

        public function findAllOrdered()
    {
        $qb = $this->createQueryBuilder('userArticles')
            ->addOrderBy('userArticles.dateAdded', 'DESC')
            ->addOrderBy('userArticles.bookTitle');
        $query = $qb->getQuery();
        return $query->execute();
    }


    public function findCurrentUser($user)
    {

        $qb = $this->createQueryBuilder('userArticles')
            ->addOrderBy('userArticles.dateAdded', 'DESC')
            ->addOrderBy('userArticles.bookTitle')
            ->where('userArticles.authorId = ' . $user);
        $query = $qb->getQuery();
        return $query->execute();
    }

    public function findAllBooks()
    {
        $qb = $this->createQueryBuilder('userArticles')
            ->groupBy('userArticles.bookTitle')
            ->orderBy('userArticles.bookTitle','ASC')
            ->addOrderBy('userArticles.dateAdded', 'ASC');
        $query = $qb->getQuery();
        return $query->execute();
    }

    public function findByTitle($title)
    {
        $qb = $this->createQueryBuilder('userArticles')
            ->andWhere('userArticles.bookTitle = :searchTerm')
            ->setParameter('searchTerm', $title)
            ->groupBy('userArticles.chapterTitle');
        $query = $qb->getQuery();
        return $query->execute();
    }
}