<?php

namespace MainBundle\Repository;

/**
 * ChapterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChapterRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAllOrdered()
    {
        $qb = $this->createQueryBuilder('userArticles')
            ->addOrderBy('userArticles.bookTitle')
            ->where('userArticles.authorId = 2');
        $query = $qb->getQuery();
        return $query->execute();
    }
}